/**
 * constants.js — Application-wide constants
 *
 * Centralizes all magic strings, enums, and config values.
 * This makes the codebase easy to update — change here, reflects everywhere.
 *
 * Rule: NEVER hardcode these values in controllers/services/adapters.
 */

// ─── Supported sports ─────────────────────────────────────────────────────────
// These are the sport identifiers used across the entire app.
// When adding a new sport, add it here first, then create its adapter.
const SPORTS = {
  NBA: 'nba',
  NFL: 'nfl',
  MLB: 'mlb',
  NHL: 'nhl',
  SOCCER: 'soccer',
};

// ─── Sports display names (for UI / logs) ────────────────────────────────────
const SPORT_LABELS = {
  [SPORTS.NBA]: 'NBA Basketball',
  [SPORTS.NFL]: 'NFL Football',
  [SPORTS.MLB]: 'MLB Baseball',
  [SPORTS.NHL]: 'NHL Hockey',
  [SPORTS.SOCCER]: 'Soccer',
};

// ─── Sports that are fully implemented ───────────────────────────────────────
// Only NBA is finalized in Phase 1. Others are stubs awaiting API selection.
const ACTIVE_SPORTS = [SPORTS.NBA];

// ─── Bet market types ─────────────────────────────────────────────────────────
// These are the betting market types we support.
// "Player prop" = a bet on an individual player's statistic (e.g., points over/under)
// "Spread"      = a bet on the margin of victory
// "Moneyline"   = a bet on which team wins outright
// "Total"       = a bet on the combined score of both teams (over/under)
const MARKET_TYPES = {
  PLAYER_PROP: 'player_prop',
  SPREAD: 'spread',
  MONEYLINE: 'moneyline',
  TOTAL: 'total',
};

// ─── Bet directions ───────────────────────────────────────────────────────────
// "OVER" = you bet the stat/score will be HIGHER than the line
// "UNDER" = you bet the stat/score will be LOWER than the line
const BET_DIRECTION = {
  OVER: 'over',
  UNDER: 'under',
};

// ─── Insight status values ────────────────────────────────────────────────────
const INSIGHT_STATUS = {
  PENDING: 'pending',     // Queued but not yet generated
  GENERATED: 'generated', // Successfully generated by AI
  FAILED: 'failed',       // AI or data fetch failed
  STALE: 'stale',         // Odds changed — insight no longer valid
};

// ─── Credit system ────────────────────────────────────────────────────────────
const CREDITS = {
  FREE_ON_SIGNUP: parseInt(process.env.FREE_CREDITS_ON_SIGNUP || '3', 10),
  COST_PER_INSIGHT: parseInt(process.env.CREDITS_PER_INSIGHT || '1', 10),
};

// ─── Stripe credit pack definitions ──────────────────────────────────────────
// Maps Stripe Price IDs to credit amounts.
// Add new packs here as you expand pricing.
const CREDIT_PACKS = [
  {
    id: 'pack_1',
    priceId: process.env.STRIPE_PRICE_1_CREDIT,
    credits: 1,
    amount: 0.99,       // USD
    label: '1 Credit — $0.99',
  },
  {
    id: 'pack_6',
    priceId: process.env.STRIPE_PRICE_6_CREDITS,
    credits: 6,
    amount: 4.99,
    label: '6 Credits — $4.99',
  },
];

// ─── Cache TTL values (seconds) ───────────────────────────────────────────────
// HOT layer (Redis)
const CACHE_TTL = {
  ODDS: parseInt(process.env.REDIS_TTL_ODDS || '300', 10),         // 5 min
  SCHEDULE: parseInt(process.env.REDIS_TTL_SCHEDULE || '3600', 10), // 1 hr
  PROPS: parseInt(process.env.REDIS_TTL_PROPS || '600', 10),        // 10 min
};

// ─── Cache key prefixes ───────────────────────────────────────────────────────
// Centralizing these prevents typos across services.
// Usage: `${CACHE_KEYS.ODDS}:nba:event123`
const CACHE_KEYS = {
  ODDS: 'odds',
  SCHEDULE: 'schedule',
  PROPS: 'props',
  PLAYER_STATS: 'player_stats',
};

// ─── Odds change threshold for cache invalidation ────────────────────────────
// If a betting line moves by more than this amount, cached AI insights are stale.
// E.g. if the over/under was 25.5 and moves to 27.0, that's a change of 1.5 → invalidate.
const ODDS_CHANGE_THRESHOLD = 1.0;

// ─── Strategy engine thresholds ──────────────────────────────────────────────
// Used to tag insights as "High Confidence" or "Best Value" in the filter system.
// "Confidence": If a player has hit their prop in 8 out of 10 recent games = High Confidence
const MIN_CONFIDENCE_HITS = 8;
const CONFIDENCE_WINDOW = 10; // Look at last N games
// "Edge": If the AI-predicted stat exceeds the betting line by 15%+ = Best Value
// e.g., AI predicts 29 points, line is 25.5 → edge = (29 - 25.5) / 25.5 = 13.7%
const MIN_EDGE_PERCENTAGE = 15;

// ─── User roles ───────────────────────────────────────────────────────────────
const USER_ROLES = {
  USER: 'user',
  ADMIN: 'admin',
};

// ─── Transaction types (for credit ledger) ────────────────────────────────────
// We log every credit change — this makes debugging and auditing easy.
const TRANSACTION_TYPES = {
  SIGNUP_BONUS: 'signup_bonus',     // Free credits given on registration
  PURCHASE: 'purchase',             // Bought via Stripe
  INSIGHT_UNLOCK: 'insight_unlock', // Spent to unlock an insight
  REFUND: 'refund',                 // Refunded due to AI failure / unavailable player
  ADMIN_GRANT: 'admin_grant',       // Manually added by admin
};

// ─── HTTP status codes (named for readability) ────────────────────────────────
const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
};

// ─── AI prompt constants ──────────────────────────────────────────────────────
const AI_PROMPT = {
  // System role sent to OpenAI — sets the AI's persona and expertise
  SYSTEM_ROLE: `You are an expert sports analytics AI. Your job is to analyze 
player statistics and betting lines to provide sharp, data-driven betting insights.
Be concise, specific, and always reference the statistical evidence behind your recommendation.
Never give generic advice. Always give a clear OVER or UNDER recommendation with reasoning.`,
};

module.exports = {
  SPORTS,
  SPORT_LABELS,
  ACTIVE_SPORTS,
  MARKET_TYPES,
  BET_DIRECTION,
  INSIGHT_STATUS,
  CREDITS,
  CREDIT_PACKS,
  CACHE_TTL,
  CACHE_KEYS,
  ODDS_CHANGE_THRESHOLD,
  MIN_CONFIDENCE_HITS,
  CONFIDENCE_WINDOW,
  MIN_EDGE_PERCENTAGE,
  USER_ROLES,
  TRANSACTION_TYPES,
  HTTP_STATUS,
  AI_PROMPT,
};