/**
 * Insight.model.js — AI-generated betting insight schema
 *
 * This is the COLD CACHE layer from the architecture plan.
 * Stores AI insights so they can be served instantly without re-generating.
 *
 * Also stores full AI input/output for:
 *  - Debugging prompt issues
 *  - Auditing AI quality over time
 *  - Cost tracking (token usage)
 *
 * AI log fields are automatically deleted after AI_LOG_RETENTION_DAYS
 * via a TTL index on aiLogExpiresAt.
 */

const mongoose = require('mongoose');
const { SPORTS, MARKET_TYPES, BET_DIRECTION, INSIGHT_STATUS } = require('../config/constants');

const insightSchema = new mongoose.Schema(
  {
    // ── Identifiers ───────────────────────────────────────────────────────────
    sport: {
      type: String,
      enum: Object.values(SPORTS),
      required: true,
      index: true,
    },

    // ID from The Odds API for the match/game
    eventId: {
      type: String,
      required: true,
      index: true,
    },

    // ── Bet context ───────────────────────────────────────────────────────────
    // The player this insight is about (for player props)
    playerName: {
      type: String,
      trim: true,
    },

    // The specific stat being bet on (e.g., "points", "rebounds", "assists")
    statType: {
      type: String,
      trim: true,
    },

    // The type of bet market (player prop, total, spread, moneyline)
    marketType: {
      type: String,
      enum: Object.values(MARKET_TYPES),
      required: true,
    },

    // The betting line at the time of insight generation.
    // e.g., for "LeBron points over/under 25.5", the line is 25.5
    bettingLine: {
      type: Number,
      required: true,
    },

    // ── AI Output ─────────────────────────────────────────────────────────────

    // The AI's recommendation: OVER or UNDER
    recommendation: {
      type: String,
      enum: Object.values(BET_DIRECTION),
    },

    // The full insight text generated by the AI (raw, kept as fallback)
    insightText: {
      type: String,
      trim: true,
    },

    // ── Structured AI response fields (parsed from JSON) ─────────────────────
    // One sentence summary of the recommendation and key reason
    insightSummary: { type: String, default: '' },

    // 2-3 supporting factors — each citing specific data windows and numbers
    insightFactors: [{ type: String }],

    // 1-2 risk factors — what could make the prediction wrong
    insightRisks: [{ type: String }],

    // AI's own confidence assessment (different from our calculated confidenceScore)
    aiConfidenceLabel: {
      type: String,
      enum: ['low', 'medium', 'high'],
      default: 'medium',
    },

    // Quality of the underlying data used for this insight
    dataQuality: {
      type: String,
      enum: ['weak', 'moderate', 'strong'],
      default: 'moderate',
    },

    // Injury metadata captured at insight generation time
    injuryStatus: {
      type: String,
      enum: ['Out', 'Doubtful', 'Questionable', 'Day-to-Day', null],
      default: null,
    },
    injuryReason: {
      type: String,
      default: null,
    },
    injuryApiStatus: {
      type: String,
      enum: ['success', 'failed', 'not_available'],
      default: 'not_available',
    },
    outcomeResult: {
      type: String,
      enum: ['win', 'loss', 'push', 'unresolved', 'void', null],
      default: null,
      index: true,
    },
    outcomeActual: {
      type: Number,
      default: null,
    },
    outcomeGameStatus: {
      type: String,
      default: null,
    },
    outcomeGradedAt: {
      type: Date,
      default: null,
    },
    // Why grading is pending/voided (e.g. no_stat_found, game_not_found)
    outcomeReason: {
      type: String,
      default: null,
      index: true,
    },
    // Number of grading attempts made for this insight
    outcomeAttempts: {
      type: Number,
      default: 0,
      index: true,
    },
    // Backoff gate: do not retry grading until this timestamp
    outcomeNextRetryAt: {
      type: Date,
      default: null,
      index: true,
    },
    // Evidence blob used for auditing outcome decisions
    outcomeSource: {
      provider: { type: String, default: null },
      gameId: { type: String, default: null },
      gameDate: { type: Date, default: null },
      dateDiffHours: { type: Number, default: null },
      statsRowsChecked: { type: Number, default: null },
    },
    // ─────────────────────────────────────────────────────────────────────────

    // The AI's confidence score (0–100) generated by our strategy engine
    // Not the AI's own confidence — calculated from historical hit rate
    confidenceScore: {
      type: Number,
      min: 0,
      max: 100,
    },

    // Edge % = how much the AI-predicted stat exceeds or falls below the line
    // Formula: (predictedValue - line) / line * 100
    edgePercentage: {
      type: Number,
    },

    // ── Smart Filter Tags ─────────────────────────────────────────────────────
    // Pre-computed tags for the filter bar (High Confidence, Best Value)
    isHighConfidence: {
      type: Boolean,
      default: false,
    },
    isBestValue: {
      type: Boolean,
      default: false,
    },

    // ── Status ────────────────────────────────────────────────────────────────
    status: {
      type: String,
      enum: Object.values(INSIGHT_STATUS),
      default: INSIGHT_STATUS.PENDING,
      index: true,
    },

    // ── Odds snapshot (for stale detection) ──────────────────────────────────
    // We store the betting line at the time of generation.
    // During pre-flight check, if current line differs by > ODDS_CHANGE_THRESHOLD,
    // we mark this insight as stale and regenerate.
    oddsSnapshot: {
      line: Number,
      fetchedAt: Date,
      bookmaker: String, // e.g., "DraftKings", "FanDuel"
    },

    // ── AI Input/Output Log ───────────────────────────────────────────────────
    // Stored for debugging and quality auditing.
    // Auto-deleted after AI_LOG_RETENTION_DAYS via TTL index.
    aiLog: {
      // The exact prompt sent to OpenAI
      prompt: { type: String },
      // The raw response from OpenAI
      rawResponse: { type: String },
      // Token usage from OpenAI (used for cost tracking)
      tokensUsed: {
        prompt: Number,
        completion: Number,
        total: Number,
      },
      // Which OpenAI model was used (stored for version tracking)
      model: { type: String },
      // How long the AI took to respond (ms)
      latencyMs: { type: Number },
      // The structured data we sent to AI (post-formula processing)
      processedStats: { type: mongoose.Schema.Types.Mixed },
    },

    // TTL field: when aiLog fields should be considered expired.
    // A separate cleanup job uses this field to null out aiLog.
    aiLogExpiresAt: {
      type: Date,
      default: () => {
        const days = parseInt(process.env.AI_LOG_RETENTION_DAYS || '30', 10);
        const date = new Date();
        date.setDate(date.getDate() + days);
        return date;
      },
    },

    // League-scoped stats payload for UI rendering (PropCard/InsightModal)
    // Keeps each league independent and future leagues plug-in friendly.
    leagueContext: {
      type: mongoose.Schema.Types.Mixed,
      default: null,
    },

    // ── Flat stat fields used by InsightModal panels ─────────────────────────
    // These are persisted directly so the frontend can read insight.foo without
    // descending into aiLog (which is stripped on most read paths).
    //
    // Shared
    formGamesCount:     { type: Number, default: null },
    edgeGamesCount:     { type: Number, default: null },
    baselineGamesCount: { type: Number, default: null },
    formStatAvg:        { type: Number, default: null },
    focusStatAvg:       { type: Number, default: null },
    baselineStatAvg:    { type: Number, default: null },
    isPlayoffGame:      { type: Boolean, default: false },
    playoffRound:       { type: String,  default: null },

    // NBA
    formPoints:         { type: Number, default: null },
    formRebounds:       { type: Number, default: null },
    formAssists:        { type: Number, default: null },
    formThrees:         { type: Number, default: null },
    formPointsAssists:  { type: Number, default: null },
    formMinutes:        { type: Number, default: null },
    avgPlusMinus:       { type: Number, default: null },
    baselineMinutes:    { type: Number, default: null },
    trueShootingPct:    { type: Number, default: null },
    effectiveFGPct:     { type: Number, default: null },
    approxUSGPct:       { type: Number, default: null },

    // MLB batter
    hitsPerG:           { type: Number, default: null },
    tbPerG:             { type: Number, default: null },
    runsPerG:           { type: Number, default: null },
    hrPerG:             { type: Number, default: null },
    rbiPerG:            { type: Number, default: null },
    battingAvg:         { type: Number, default: null },
    obp:                { type: Number, default: null },
    slg:                { type: Number, default: null },
    ops:                { type: Number, default: null },
    // MLB pitcher
    kPerStart:          { type: Number, default: null },
    ipPerStart:         { type: Number, default: null },
    era:                { type: Number, default: null },
    whip:               { type: Number, default: null },
    k9:                 { type: Number, default: null },
    formKPerStart:      { type: Number, default: null },

    // NHL skater (per-game averages)
    goalsPerG:          { type: Number, default: null },
    assistsPerG:        { type: Number, default: null },
    pointsPerG:         { type: Number, default: null },
    shotsPerG:          { type: Number, default: null },
    toiPerG:            { type: Number, default: null },
    ppgPerG:            { type: Number, default: null },
    pmPerG:             { type: Number, default: null },
    esGoalsPerG:        { type: Number, default: null },
    ppGoalsPerG:        { type: Number, default: null },

    // NHL — splits + signals (added with playoff/recency upgrades)
    homeStatAvg:        { type: Number, default: null },
    awayStatAvg:        { type: Number, default: null },
    homeGames:          { type: Number, default: null },
    awayGames:          { type: Number, default: null },
    h2hStatAvg:         { type: Number, default: null },
    h2hCount:           { type: Number, default: null },
    opposingTeamAbbrev: { type: String, default: null },
    formWindowSize:     { type: Number, default: null },

    // NHL — season composition (mixed playoff/regular)
    playoffGameCount:   { type: Number, default: null },
    regularGameCount:   { type: Number, default: null },
    isMixedSeason:      { type: Boolean, default: false },
    formMix:            { type: mongoose.Schema.Types.Mixed, default: null },
    edgeMix:            { type: mongoose.Schema.Types.Mixed, default: null },
    baselineMix:        { type: mongoose.Schema.Types.Mixed, default: null },

    // NHL — quality flags
    tooThin:            { type: Boolean, default: false },
    forceConfidence:    { type: String,  default: null },   // null | 'low'
    hasInconsistentTOI: { type: Boolean, default: false },
    toiCV:              { type: Number,  default: null },
    toiCVThreshold:     { type: Number,  default: null },
    lineTier:           { type: String,  default: null },
    position:           { type: String,  default: null },   // 'F' | 'D' | 'G'

    // NHL — scoring profile
    ppDependencyPct:    { type: Number, default: null },
    isPPDependent:      { type: Boolean, default: false },
    shootingPct:        { type: Number, default: null },
    onGoalStreak:       { type: Boolean, default: false },
    onGoalSlump:        { type: Boolean, default: false },
    formGoals:          { type: Number, default: null },
    edgeGoals:          { type: Number, default: null },

    // NHL — matchup flags surfaced from pipeline
    isPlayoff:          { type: Boolean, default: false },
    isBackToBack:       { type: Boolean, default: false },
    playerTeam:         { type: String, enum: ['home', 'away', null], default: null },

    // ── Error tracking ────────────────────────────────────────────────────────
    errorMessage: {
      type: String,
    },

    // How many users have unlocked this insight (analytics)
    unlockCount: {
      type: Number,
      default: 0,
    },
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
  }
);

// ─── Indexes ──────────────────────────────────────────────────────────────────

// Compound index: fast lookup by sport + event + player + stat + line
// This is the primary lookup key when checking if an insight already exists
insightSchema.index(
  { sport: 1, eventId: 1, playerName: 1, statType: 1, bettingLine: 1 },
  { unique: true }
);

// For filter queries: high confidence bets
insightSchema.index({ isHighConfidence: 1, status: 1 });

// For filter queries: best value bets
insightSchema.index({ isBestValue: 1, status: 1 });

insightSchema.index({ outcomeResult: 1, outcomeGradedAt: -1 });

// TTL index: MongoDB will automatically expire documents where aiLogExpiresAt is past.
// Instead of deleting the whole document, we use a cleanup job to just null aiLog fields.
// This index is used by the cleanup cron job for efficient querying.
insightSchema.index({ aiLogExpiresAt: 1 });

// ─── Static methods ───────────────────────────────────────────────────────────

/**
 * Find an existing valid insight for a given bet.
 * Returns null if not found or if the status is stale/failed.
 *
 * @param {Object} params
 * @returns {Promise<Insight|null>}
 */
insightSchema.statics.findExisting = async function ({
  sport,
  eventId,
  playerName,
  statType,
  bettingLine,
}) {
  return this.findOne({
    sport,
    eventId,
    playerName,
    statType,
    bettingLine,
    status: INSIGHT_STATUS.GENERATED,
  }).lean(); // .lean() returns plain JS object — faster for read-only operations
};

const Insight = mongoose.model('Insight', insightSchema);

module.exports = Insight;